python autoencoder/train-autoencoder.py --dataset mnist --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset mnist --task anomaly-detection --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset fashion-mnist --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset fashion-mnist --task anomaly-detection --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset cifar10 --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset cifar10 --task anomaly-detection --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset cifar100 --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset cifar100 --task anomaly-detection --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset super-tiny-imagenet --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset super-tiny-imagenet --task anomaly-detection --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset tiny-imagenet --task reconstruction --generate-imgs --save-results --result-strategy all
python autoencoder/train-autoencoder.py --dataset tiny-imagenet --task anomaly-detection --generate-imgs --save-results --result-strategy all
